import AVFoundation
import Foundation

/// Sound effects for the TV board.
///
/// The TV is the only device in the room with a speaker worth using -- the
/// phones are controllers held in someone's hand -- so all audio lives in
/// this target. Clips are generated by `tools/generate_sounds.py` and
/// bundled from `Resources/Sounds`.
@MainActor
final class SoundPlayer {

    static let shared = SoundPlayer()

    enum Effect: String {
        case rouletteClick = "roulette_click"
        case rouletteSpin  = "roulette_spin"
        case winFanfare    = "win_fanfare"
        /// A Connect 4 disc landing in its slot -- played by
        /// `TVConnect4BoardView` once a dropped disc's fall animation
        /// finishes. `winFanfare` above is reused for a Connect 4 win.
        case connect4Drop  = "connect4_drop"
    }

    /// One reusable player per effect, plus a small pool for the click, which
    /// needs to overlap with itself as the ball speeds over the frets.
    private var players: [Effect: AVAudioPlayer] = [:]
    private var clickPool: [AVAudioPlayer] = []
    private var clickIndex = 0

    private init() {
        configureSession()
    }

    private func configureSession() {
        // .ambient so GameLab never stops whatever the room is already
        // playing; this is decoration, not the main event.
        let session = AVAudioSession.sharedInstance()
        try? session.setCategory(.ambient, mode: .default, options: [.mixWithOthers])
        try? session.setActive(true)
    }

    private func makePlayer(for effect: Effect) -> AVAudioPlayer? {
        guard let url = Bundle.main.url(forResource: effect.rawValue, withExtension: "wav"),
              let player = try? AVAudioPlayer(contentsOf: url)
        else { return nil }
        player.prepareToPlay()
        return player
    }

    private func player(for effect: Effect) -> AVAudioPlayer? {
        if let existing = players[effect] { return existing }
        let created = makePlayer(for: effect)
        players[effect] = created
        return created
    }

    /// Fire and forget. Restarts the clip if it is already playing.
    func play(_ effect: Effect, volume: Float = 1.0) {
        guard let player = player(for: effect) else { return }
        player.volume = volume
        player.currentTime = 0
        player.play()
    }

    /// The ball ticking over the frets fires faster than a single player can
    /// restart cleanly, so these round-robin through a small pool.
    func playClick(volume: Float = 1.0) {
        if clickPool.isEmpty {
            clickPool = (0..<4).compactMap { _ in makePlayer(for: .rouletteClick) }
        }
        guard !clickPool.isEmpty else { return }
        let player = clickPool[clickIndex % clickPool.count]
        clickIndex += 1
        player.volume = volume
        player.currentTime = 0
        player.play()
    }

    /// Starts the wheel loop, or does nothing if it is already running.
    func startLoop(_ effect: Effect, volume: Float = 0.5) {
        guard let player = player(for: effect) else { return }
        guard !player.isPlaying else { return }
        player.numberOfLoops = -1
        player.volume = volume
        player.currentTime = 0
        player.play()
    }

    func fadeOutLoop(_ effect: Effect, over seconds: TimeInterval = 0.6) {
        guard let player = players[effect], player.isPlaying else { return }
        player.setVolume(0, fadeDuration: seconds)
        Task { @MainActor in
            try? await Task.sleep(nanoseconds: UInt64(seconds * 1_000_000_000))
            player.stop()
            player.numberOfLoops = 0
        }
    }

    func stopAll() {
        players.values.forEach { $0.stop() }
        clickPool.forEach { $0.stop() }
    }
}
